name: Publish Prerelease

on:
    push:
        tags:
            - v*.*.*-**

env:
    GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}

jobs:
    lint:
        uses: ./.github/workflows/stage-lint.yml
    test:
        uses: ./.github/workflows/stage-test.yml

    publish-sdks:
        needs: [test, lint]
        uses: ./.github/workflows/stage-publish-sdk.yml
        with:
            version: ${{ github.ref_name }}
            prerelease: true
        secrets: inherit
