name: Test

on:
    workflow_call:

jobs:
    test:
        name: Test Typescript
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.commit-ref }}
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org
            - name: Run Tests
              run: npm i && npm run test
